// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package robno

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"helia/frontend/components"
	tmpl "helia/frontend/templates"
	"helia/i18n"
	"helia/internal/common"
	"helia/internal/domain"
)

func MagacinKonto(tbl domain.TableData, searchInput domain.InputControl, btnPrint domain.Button, translator *i18n.Service) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Container with full height --><div class=\"bg-blue-100 p-1 flex flex-col h-full\"><div class=\"border bg-blue-100 border border-blue-400 p-1 rounded-lg flex flex-col min-h-0 overflow-hidden flex-1\"><!-- Search bar with button in flex row --><div class=\"flex items-center justify-between\"><div class=\"flex-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Search_Part(tbl, searchInput).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"flex-shrink-0 mb-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Search_PartPrintButton(btnPrint).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><!-- Table --><div class=\"flex-1 overflow-x-auto overflow-y-auto min-h-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Table(tbl, translator).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div><div id=\"dialog-partneri-stampa\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = tmpl.OpenPrintWithParamsScript().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func MagacinKontoDialog(dialog domain.Dialog, action string, model domain.Magkonto, btnSave domain.Button, btnCancel domain.Button, btnClose domain.Button, translator *i18n.Service, csrfToken string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = tmpl.Dialog("magacin-konto-form", csrfToken, magacinKontoFormContent(model, translator), dialog, btnSave, btnCancel, btnClose, translator).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func magacinKontoFormContent(model domain.Magkonto, translator *i18n.Service) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"grid grid-cols-2 gap-2\"><!-- Magacin (required) --><div class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LabelField(domain.LabelFieldConfig{
			ID:         "mag",
			LabelText:  translator.Label("Magacin"),
			ClassLabel: common.ClassLabel + " w-24",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInputField(domain.InputFieldConfig{
			ID:         "mag",
			Name:       "mag",
			Value:      fmt.Sprintf("%d", model.Mag),
			FieldType:  "number",
			Required:   true,
			Disabled:   false,
			ClassInput: common.ClassInputTextEnabled + " w-24",
			TabIndex:   "1",
			OnInput:    "clearFieldError",
			OnFocus:    "clearFieldError",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><!-- Konto zaliha (required) --><div class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LabelField(domain.LabelFieldConfig{
			ID:         "konto",
			LabelText:  translator.Label("Konto zaliha"),
			ClassLabel: common.ClassLabel + " w-24",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInputField(domain.InputFieldConfig{
			ID:         "konto",
			Name:       "konto",
			Value:      model.Konto,
			FieldType:  "text",
			Required:   true,
			Disabled:   false,
			ClassInput: common.ClassInputTextEnabled + " flex-1",
			TabIndex:   "2",
			OnInput:    "clearFieldError",
			OnFocus:    "clearFieldError",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><!-- ID FKPL --><div class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LabelField(domain.LabelFieldConfig{
			ID:         "idfkpl",
			LabelText:  translator.Label("ID FKPL"),
			ClassLabel: common.ClassLabel + " w-24",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInputField(domain.InputFieldConfig{
			ID:         "idfkpl",
			Name:       "idfkpl",
			Value:      fmt.Sprintf("%d", model.IDFkpl),
			FieldType:  "number",
			Required:   false,
			Disabled:   false,
			ClassInput: common.ClassInputTextEnabled + " w-24",
			TabIndex:   "3",
			OnInput:    "clearFieldError",
			OnFocus:    "clearFieldError",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><!-- V Konta --><div class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LabelField(domain.LabelFieldConfig{
			ID:         "vkonta",
			LabelText:  translator.Label("V Konta"),
			ClassLabel: common.ClassLabel + " w-24",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInputField(domain.InputFieldConfig{
			ID:         "vkonta",
			Name:       "vkonta",
			Value:      fmt.Sprintf("%d", model.VKonta),
			FieldType:  "number",
			Required:   false,
			Disabled:   false,
			ClassInput: common.ClassInputTextEnabled + " w-24",
			TabIndex:   "4",
			OnInput:    "clearFieldError",
			OnFocus:    "clearFieldError",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div><!-- Konto prihoda --><div class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LabelField(domain.LabelFieldConfig{
			ID:         "kontoprih",
			LabelText:  translator.Label("Konto prihoda"),
			ClassLabel: common.ClassLabel + " w-24",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInputField(domain.InputFieldConfig{
			ID:         "kontoprih",
			Name:       "kontoprih",
			Value:      model.KontoPrih,
			FieldType:  "text",
			Required:   false,
			Disabled:   false,
			ClassInput: common.ClassInputTextEnabled + " flex-1",
			TabIndex:   "5",
			OnInput:    "clearFieldError",
			OnFocus:    "clearFieldError",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div><!-- Konto troška --><div class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LabelField(domain.LabelFieldConfig{
			ID:         "kontotroska",
			LabelText:  translator.Label("Konto troška"),
			ClassLabel: common.ClassLabel + " w-24",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInputField(domain.InputFieldConfig{
			ID:         "kontotroska",
			Name:       "kontotroska",
			Value:      model.KontoTroska,
			FieldType:  "text",
			Required:   false,
			Disabled:   false,
			ClassInput: common.ClassInputTextEnabled + " flex-1",
			TabIndex:   "6",
			OnInput:    "clearFieldError",
			OnFocus:    "clearFieldError",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div><!-- Konto RUC --><div class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LabelField(domain.LabelFieldConfig{
			ID:         "kontoruc",
			LabelText:  translator.Label("Konto RUC"),
			ClassLabel: common.ClassLabel + " w-24",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInputField(domain.InputFieldConfig{
			ID:         "kontoruc",
			Name:       "kontoruc",
			Value:      model.KontoRuc,
			FieldType:  "text",
			Required:   false,
			Disabled:   false,
			ClassInput: common.ClassInputTextEnabled + " flex-1",
			TabIndex:   "7",
			OnInput:    "clearFieldError",
			OnFocus:    "clearFieldError",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div><!-- Konto rabat --><div class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LabelField(domain.LabelFieldConfig{
			ID:         "kontorab",
			LabelText:  translator.Label("Konto rabat"),
			ClassLabel: common.ClassLabel + " w-24",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInputField(domain.InputFieldConfig{
			ID:         "kontorab",
			Name:       "kontorab",
			Value:      model.KontoRab,
			FieldType:  "text",
			Required:   false,
			Disabled:   false,
			ClassInput: common.ClassInputTextEnabled + " flex-1",
			TabIndex:   "8",
			OnInput:    "clearFieldError",
			OnFocus:    "clearFieldError",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
